# Generated by Django 5.2.4 on 2025-08-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': '1. Kategoriyalar'},
        ),
        migrations.AlterField(
            model_name='new',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
