# Generated by Django 5.2.4 on 2025-09-02 16:30

import common.models.auth
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common', '0002_alter_category_options_alter_new_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15)),
                ('key', models.CharField(max_length=256)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('by', models.CharField(choices=[('login', 'Login'), ('regis', 'Register')])),
                ('extra', models.JSONField(default=dict)),
                ('tries', models.SmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fullname', models.CharField(max_length=56)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('user_type', models.SmallIntegerField(choices=[(1, 'Admin'), (2, 'User')], default=2, verbose_name='Admin(1), User(2)')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', common.models.auth.CustomUserManager()),
            ],
        ),
    ]
